export const db = "69212afa000c996b5232"
export const questionCollection = "questions"
export const answerCollection = "answers"
export const commentCollection = "comments"
export const voteCollection = "votes"
export const notificationCollection = "notifications"
export const questionAttachmentBucket = "question-attachment"